server:
  port: 9001
spring:
  application:
    name: swagger-make-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: xucong
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
